require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
require 'pathname'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']

  podfile_properties['apple.ccacheEnabled'] == 'true'
end

def patch_expo_modules_provider_for_default_main_actor
  provider_path = File.join(
    Pod::Config.instance.installation_root,
    'Pods/Target Support Files/Pods-qvac2026/ExpoModulesProvider.swift'
  )
  return unless File.exist?(provider_path)

  provider = File.read(provider_path)
  unless provider.include?('public nonisolated required init()')
    provider.gsub!(
      "public class ExpoModulesProvider: ModulesProvider {\n",
      "public class ExpoModulesProvider: ModulesProvider {\n  public nonisolated required init() { super.init() }\n"
    )
  end
  provider.gsub!('public override func ', 'public nonisolated override func ')
  File.write(provider_path, provider)
end

ENV['RCT_NEW_ARCH_ENABLED'] ||= '0' if podfile_properties['newArchEnabled'] == 'false'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true' && podfile_properties['newArchEnabled'] != 'false'
ENV['PROJECT_ROOT'] ||= Pod::Config.instance.installation_root.to_s
platform :ios, podfile_properties['ios.deploymentTarget'] || '17.0'

prepare_react_native_project!

target 'qvac2026' do
  use_expo_modules!

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  native_modules_config = list_native_modules!(config_command)
  native_modules_config[:ios_project_root_path] = Pod::Config.instance.installation_root.to_s
  config = link_native_modules!(native_modules_config)
  autolinked_ios_project_root = File.join(Pod::Config.instance.installation_root, 'ios')
  react_native_absolute_path = File.expand_path(config[:reactNativePath], autolinked_ios_project_root)
  react_native_path = Pathname.new(react_native_absolute_path).relative_path_from(Pod::Config.instance.installation_root).to_s
  $CODEGEN_OUTPUT_DIR = File.join(Pod::Config.instance.installation_root, 'build/generated/ios')

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => react_native_path,
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      react_native_path,
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )
  end
end

post_integrate do |installer|
  patch_expo_modules_provider_for_default_main_actor
end
